---
- hosts: monitoring.fra1.internal
  become: yes
  tasks:
    - name: Create Nagios configuration for app-vm1.fra1.internal
      template:
        src: nagios_templates/app-vm1.fra1.internal.cfg.j2
        dest: /etc/nagios/conf.d/app-vm1.fra1.internal.cfg
        owner: nagios
        group: nagios
        mode: 0644

    - name: Create Nagios configuration for db-vm1.fra1.db
      template:
        src: nagios_templates/db-vm1.fra1.db.cfg.j2
        dest: /etc/nagios/conf.d/db-vm1.fra1.db.cfg
        owner: nagios
        group: nagios
        mode: 0644

    - name: Create Nagios configuration for web-vm1.fra1.web
      template:
        src: nagios_templates/web-vm1.fra1.web.cfg.j2
        dest: /etc/nagios/conf.d/web-vm1.fra1.web.cfg
        owner: nagios
        group: nagios
        mode: 0644

    - name: Restart Nagios service
      service:
        name: nagios
        state: restarted
